# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e82d3f39a74c4f22edbd6fc37254e47ef56099a93454a8613c63382fa074ecf0ec2e4f453f9fe9c0cc2040733ab20dd424d0103ea35a1a0c61e269435f85fd8

test:
  secret_key_base: 6416a35bfd9af63027a295f1e1d99299c961f13bfc16a0ae41e270a82f642a996cd0d91f1d57d3381a40b693ec954ca1260be107b3c11a95a9ba8770c7ca2f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
