development:
  solr:
    hostname: localhost
    port: 8080
    log_level: INFO
    path: /solr/development
    # read_timeout: 2
    # open_timeout: 0.5

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/solr_sunspot_example

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    